### ISSUE TITLE
Unity 5.0.1f1 always returning an empty joystick name

### ISSUE THREAD

**Issue by MadballNeek** [pbhogan/InControl#197]
After upgrading to Unity version 5.0.1f1, `Input.GetJoystickNames()` is always returning a joystick with no name, even though there's no devices connected to the computer (I tested this on two different machines, Windows 7 standalone). Thus, InControl will register it as an unknown device.

While this does seem like a Unity issue, I wanted to submit a new issue just so we're aware of it. My current workaround is to comment out the following two lines in `UnityInputDeviceManager.DetectAttachedJoystickDevice`

    if (matchedDeviceProfile == null)
    {
         //deviceProfile = new UnityUnknownDeviceProfile( unityJoystickName );
        //deviceProfiles.Add( deviceProfile );
    }
    else
    {
        deviceProfile = matchedDeviceProfile;
    }

**Comment by pbhogan** [comment]
Yes, this is new expected behavior in Unity on Windows as of Unity 4.6.3p1 and Unity 5.0.1f1

It is dealt with here: https://github.com/pbhogan/InControl/blob/master/Assets/InControl/Source/Unity/UnityInputDeviceManager.cs#L135

So it shouldn't be creating an unknown device unless you aren't running the latest version?

But that aside, your code shouldn't care if there is an unknown device. Unknown devices could occur for all kinds of reasons, not least of which is plugging in a legitimately unknown device. You cannot assume every device InControl enumerates is a usable device until it actually provides input. Even if it is known, it could be a phantom device (due to Unity bugginess) that never responds. Hence my treatise on treating InputManager.Devices as a potential pool of devices from which to choose devices based on user input, rather than an absolute indexed list of valid devices.

**Comment by MadballNeek** [comment]
Ah okay, I'm not running latest should I'll be sure to update.

Well, I'm developing a local multiplayer game, and I use which devices are attached to know how many characters to set in my character selection screen, but it sounds like I should rethink that to force the player to press a button first.

Thanks.
