### ISSUE TITLE
Steam controller support?

### ISSUE THREAD

**Issue by cAyou66** [pbhogan/InControl#204]
Hi there ! This question might be already asked but I was wondering if you plan guys to support the Steam controller on InControl. I'm pretty sure we will need it for our game.

Thanks !

**Comment by pbhogan** [comment]
All I can tell you at this point is that I've preordered one. I have no idea if it will work or how well it can be supported until I have one, but I'll do my best to do so. :)

**Comment by cAyou66** [comment]
How can you be so fast to answer? Ahahah !
Thanks man, that's appreciated. I'm sure I won't be the first to want this controller supported on your plugin ;)

**Comment by ewersp** [comment]
You might try contacting controllerdevkits@valvesoftware.com and ask if they'll send you one before the November 10th release date.

We're currently in the process of doing this for our unreleased (but Steam Greenlight-approved) game and it seems hopeful.

**Comment by pbhogan** [comment]
Thanks for the tip. :)

**Comment by ewersp** [comment]
@pbhogan I just received a steam controller in the mail today! My initial findings are:

1) It essentially works out of the box IF you launch your game from Steam Big Picture Mode (you can select "Add a Non-Steam Game..." from the Steam client to test local Unity release builds so you don't need to be a Steam developer to test this). From there, Steam presents end users with various ways to emulate (simulate?) keyboard, mouse & XInput inputs with the controller, and the default option essentially functions like a 360 controller.

2) However, where InControl comes into the picture is when selecting the "Gamepad with Mouse" emulation mapping (which feels much better than the default option). The left analog stick and buttons are treated like XInput, but the right analog stick is treated like mouse movement.

The problem is that we've created a custom UnityInputDeviceProfile for keyboard & mouse input (I know this is deprecated but we're still on an older version) and we use InputManager.ActiveDevice which unfortunately thrashes back and forth.

For this reason, Valve states verbatim: "Don't disable the mouse when the gamepad is active or vice versa. Many users will prefer mouse based camera over the emulated right analog stick, but will want to control their characters with real gamepad controls using the left analog stick."

So, I might have to remove the mouse inputs from our custom UnityInputDeviceProfile and re-wire them in our GameInputManager elsewhere. Unless the updated bindings API would fix the thrash?

3) Lastly, the controller doesn't seem to work (for our game and other released games that Valve lists as supporting it) outside of Big Picture Mode. Some buttons work but the bindings are completely wrong. This means it doesn't work in the Unity Editor for testing; I just see the following log and it doesn't register in the TestInputManager scene either. =(

<RI.Hid> Device is not supported: Steam Controller (65280, 0x0001).

Anyway, I hope you or someone else finds this info useful!

**Comment by pbhogan** [comment]
Thanks—yes that pretty much matches my findings.

I think the bindings API should fix that issue since it can have both mouse input and controller input bound to an action and the mouse isn't part of a virtual device anymore so it wouldn't cause device switching.
